INSERT INTO public.role (name) VALUES ('DEFAULT');
INSERT INTO public.role (name) VALUES ('ADMIN');
INSERT INTO public.role (name) VALUES ('SUPER');

INSERT INTO public.user_roles (user_id, role_name) VALUES ('danilo.duarte8@hotmail.com', 'SUPER');
INSERT INTO public.user_roles (user_id, role_name) VALUES ('jherson_k-f@hotmail.com', 'SUPER');
INSERT INTO public.users (id, cic, date_of_birth, email, first_name, gender, last_name, password) VALUES (1, '02778078240', '2020-11-30 16:25:54.103000', 'jherson_k-f@hotmail.com', 'Jherson', 0, 'Haryson', '$2y$12$qv4MDEtGvnlVw95.i850bOS.PphxbNZQ8nikb/GcURjsk8AVQyX8m');
INSERT INTO public.users (id, cic, date_of_birth, email, first_name, gender, last_name, password) VALUES (1, '02778078240', '2020-11-30 16:25:54.103000', 'danilo.duarte8@hotmail.com', 'Danilo', 0, 'Duarte', '$2y$12$qv4MDEtGvnlVw95.i850bOS.PphxbNZQ8nikb/GcURjsk8AVQyX8m');


/* VACINES */
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (1, 'DOSAGE_UNIQUE', 0, null, 0, 'BCG-ID', null, null, 'Formas graves de Tuberculose', 'INFANT', null, '2020-12-04 17:28:36.361000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (2, 'DOSAGE_1', 0, null, 0, 'Vacina contra Hepatite B', 1, 'A primeira dose da vacina contra a hepatite B deve ser administrada na maternidade, nas primeiras 12 horas de vida do recém-nascido. O esquema básico se constitui de 03 (três) doses, com intervalos de 30 dias da primeira para a segunda dose e 180 dias da primeira para a terceira dose.', 'Hepatite B', 'INFANT', 3, '2020-12-04 17:28:34.525000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (3, 'DOSAGE_2', 1, null, 1, 'Vacina contra Hepatite B', 5, 'A primeira dose da vacina contra a hepatite B deve ser administrada na maternidade, nas primeiras 12 horas de vida do recém-nascido. O esquema básico se constitui de 03 (três) doses, com intervalos de 30 dias da primeira para a segunda dose e 180 dias da primeira para a terceira dose.', 'Hepatite B', 'INFANT', 17, '2020-12-04 17:28:33.728000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (4, 'DOSAGE_1', 2, null, 2, 'Vacina Tetravalente', 2, 'O esquema de vacinação atual é feito aos 2, 4 e 6 meses de idade com a vacina Tetravalente e dois reforços com a Tríplice Bacteriana (DTP). O primeiro reforço aos 15 meses e o segundo reforço entre 4 e 6 anos.', 'Difteria, tétano, coqueluche, meningite e outras infecções por Haemophilus influenzae tipo B', 'INFANT', 9, '2020-12-04 17:28:32.243000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (5, 'DOSAGE_1', 2, null, 2, 'Vacina Oral contra Rotavírus Humano', 2, 'É possível administar a primeira dose da Vacina Oral de Rotavírus Humano a partir de 1 mês e 15 dias a 3 meses e 7 dias de idade (6 a 14 semanas de vida)', 'Doenças diarréicas por Rotavírus', 'INFANT', 11, '2020-12-04 17:28:33.024000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (6, 'DOSAGE_1', 2, null, 2, 'Vacina contra Pneumococos', 2, null, 'Otite, sinusite, pneumonias, meningite causadas pelo Streptococcus pneumoniae', 'INFANT', 12, '2020-12-04 17:28:30.607000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (7, 'DOSAGE_1', 2, null, 2, 'Vacina Oral contra a Pólio', 2, null, 'Poliomielite (paralisia Infantil)', 'INFANT', 10, '2020-12-04 17:28:31.458000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (8, 'DOSAGE_1', 3, null, 3, 'Vacina contra Meningococo C', 2, null, 'Doença invasiva causada por Neisseria meningitidis do Sorogrupo C', 'INFANT', 13, '2020-12-04 17:28:29.793000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (9, 'DOSAGE_2', 4, null, 4, 'Vacina Tetravalente', 2, 'O esquema de vacinação atual é feito aos 2, 4 e 6 meses de idade com a vacina Tetravalente e dois reforços com a Tríplice Bacteriana (DTP). O primeiro reforço aos 15 meses e o segundo reforço entre 4 e 6 anos.', 'Difteria, tétano, coqueluche, meningite e outras infecções por Haemophilus influenzae tipo B', 'INFANT', 14, '2020-12-04 17:28:26.400000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (10, 'DOSAGE_2', 4, null, 4, 'Vacina Oral contra a Pólio', 2, null, 'Poliomielite (paralisia Infantil)', 'INFANT', 16, '2020-12-04 17:28:28.088000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (11, 'DOSAGE_2', 4, null, 4, 'Vacina Oral contra Rotavírus Humano', null, 'É possível administrar a segunda dose da Vacina Oral de Rotavírus Humano a partir de 3 meses e 7 dias a 5 meses e 15 dias de idade (14 a 24 semanas de ida). O intervalo mínimo reconizado entre a primeira e a segunda dose é de 4 semanas.', 'Doenças diarréicas por Rotavírus', 'INFANT', null, '2020-12-04 17:28:28.952000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (12, 'DOSAGE_2', 4, null, 4, 'Vacina contra Pneumococos', 2, null, 'Otite, sinusite, pneumonias, meningite causadas pelo Streptococcus pneumoniae', 'INFANT', 15, '2020-12-04 17:28:27.262000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (13, 'DOSAGE_2', 5, null, 5, 'Vacina contra Meningococo C', 10, null, 'Doença invasiva causada por Neisseria meningitidis do Sorogrupo C', 'INFANT', 22, '2020-12-04 17:28:24.577000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (14, 'DOSAGE_3', 6, null, 6, 'Vacina Tetravalente', 9, 'O esquema de vacinação atual é feito aos 2, 4 e 6 meses de idade com a vacina Tetravalente e dois reforços com a Tríplice Bacteriana (DTP). O primeiro reforço aos 15 meses e o segundo reforço entre 4 e 6 anos.', 'Difteria, tétano, coqueluche, meningite e outras infecções por Haemophilus influenzae tipo B', 'INFANT', 23, '2020-12-04 17:27:56.488000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (15, 'DOSAGE_3', 6, null, 6, 'Vacina contra Pneumococos', 6, null, 'Otite, sinusite, pneumonias, meningite causadas pelo Streptococcus pneumoniae', 'INFANT', 20, '2020-12-04 17:27:49.335000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (16, 'DOSAGE_3', 6, null, 6, 'Vacina Oral contra a Pólio', 9, null, 'Poliomielite (paralisia Infantil)', 'INFANT', 21, '2020-12-04 17:28:04.691000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (17, 'DOSAGE_2', 6, null, 6, 'Vacina contra Hepatite B', null, 'A primeira dose da vacina contra a hepatite B deve ser administrada na maternidade, nas primeiras 12 horas de vida do recém-nascido. O esquema básico se constitui de 03 (três) doses, com intervalos de 30 dias da primeira para a segunda dose e 180 dias da primeira para a terceira dose.', 'Hepatite B', 'INFANT', null, '2020-12-04 17:28:16.011000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (18, 'DOSAGE_1', 9, null, 9, 'Vacina contra febre amarela', null, 'A vacina contra febre amarela está indicada para crianças a partir dos 09 meses de idade e quando for viajar para o exterior, vacinar contra Febre Amarela 10 (dez) dias antes da viagem.', 'Febre amarela', 'INFANT', null, '2020-12-04 17:27:40.540000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (19, 'DOSAGE_1', 12, null, 12, 'Tríplice Viral', 36, null, 'Sarampo, Rubéola e Caxumba', 'INFANT', 25, '2020-12-04 17:27:26.286000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (20, 'DOSAGE_REINFORCEMENT', 12, null, 12, 'Vacina contra Pneumococos', null, null, 'Otite, sinusite, pneumonias, meningite causadas pelo Streptococcus pneumoniae', 'INFANT', null, '2020-12-04 17:27:32.960000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (21, 'DOSAGE_REINFORCEMENT', 15, null, 15, 'Vacina Oral contra a Pólio', null, null, 'Poliomielite (paralisia Infantil)', 'INFANT', null, '2020-12-04 17:27:19.486000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (22, 'DOSAGE_REINFORCEMENT', 15, null, 15, 'Vacina contra Meningococo C', null, null, 'Doença invasiva causada por Neisseria meningitidis do Sorogrupo C', 'INFANT', null, '2020-12-04 17:27:02.391000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (23, 'DOSAGE_1_REINFORCEMENT', 15, null, 15, 'Vacina Tríplice Bacteriana', 33, 'O esquema de vacinação atual é feito aos 2, 4 e 6 meses de idade com a vacina Tetravalente e dois reforços com a Tríplice Bacteriana (DTP). O primeiro reforço aos 15 meses e o segundo reforço entre 4 e 6 anos.', 'Difteria, tétano, coqueluche', 'INFANT', 24, '2020-12-04 17:27:09.448000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (24, 'DOSAGE_2_REINFORCEMENT', 72, null, 48, 'Vacina Tríplice Bacteriana', null, 'O esquema de vacinação atual é feito aos 2, 4 e 6 meses de idade com a vacina Tetravalente e dois reforços com a Tríplice Bacteriana (DTP). O primeiro reforço aos 15 meses e o segundo reforço entre 4 e 6 anos.', 'Difteria, tétano, coqueluche', 'INFANT', null, '2020-12-04 17:26:15.144000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (25, 'DOSAGE_REINFORCEMENT', 72, null, 48, 'Tríplice Viral', null, null, 'Sarampo, Rubéola e Caxumba', 'INFANT', null, '2020-12-04 17:26:24.122000', 'A');




-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (138, 'DOSAGE_UNIQUE', 0, null, 0, 'BCG-ID', null, null, 'Formas graves de Tuberculose', 'INFANT', null, '2020-12-04 17:28:36.361000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (141, 'DOSAGE_1', 0, null, 0, 'Vacina contra Hepatite B', 1, 'A primeira dose da vacina contra a hepatite B deve ser administrada na maternidade, nas primeiras 12 horas de vida do recém-nascido. O esquema básico se constitui de 03 (três) doses, com intervalos de 30 dias da primeira para a segunda dose e 180 dias da primeira para a terceira dose.', 'Hepatite B', 'INFANT', 142, '2020-12-04 17:28:34.525000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (142, 'DOSAGE_2', 1, null, 1, 'Vacina contra Hepatite B', 5, 'A primeira dose da vacina contra a hepatite B deve ser administrada na maternidade, nas primeiras 12 horas de vida do recém-nascido. O esquema básico se constitui de 03 (três) doses, com intervalos de 30 dias da primeira para a segunda dose e 180 dias da primeira para a terceira dose.', 'Hepatite B', 'INFANT', 143, '2020-12-04 17:28:33.728000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (153, 'DOSAGE_1', 2, null, 2, 'Vacina Oral contra Rotavírus Humano', 2, 'É possível administar a primeira dose da Vacina Oral de Rotavírus Humano a partir de 1 mês e 15 dias a 3 meses e 7 dias de idade (6 a 14 semanas de vida)', 'Doenças diarréicas por Rotavírus', 'INFANT', 154, '2020-12-04 17:28:33.024000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (148, 'DOSAGE_1', 2, null, 2, 'Vacina Tetravalente', 2, 'O esquema de vacinação atual é feito aos 2, 4 e 6 meses de idade com a vacina Tetravalente e dois reforços com a Tríplice Bacteriana (DTP). O primeiro reforço aos 15 meses e o segundo reforço entre 4 e 6 anos.', 'Difteria, tétano, coqueluche, meningite e outras infecções por Haemophilus influenzae tipo B', 'INFANT', 149, '2020-12-04 17:28:32.243000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (144, 'DOSAGE_1', 2, null, 2, 'Vacina Oral contra a Pólio', 2, null, 'Poliomielite (paralisia Infantil)', 'INFANT', 145, '2020-12-04 17:28:31.458000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (155, 'DOSAGE_1', 2, null, 2, 'Vacina contra Pneumococos', 2, null, 'Otite, sinusite, pneumonias, meningite causadas pelo Streptococcus pneumoniae', 'INFANT', 156, '2020-12-04 17:28:30.607000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (159, 'DOSAGE_1', 3, null, 3, 'Vacina contra Meningococo C', 2, null, 'Doença invasiva causada por Neisseria meningitidis do Sorogrupo C', 'INFANT', 160, '2020-12-04 17:28:29.793000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (154, 'DOSAGE_2', 4, null, 4, 'Vacina Oral contra Rotavírus Humano', null, 'É possível administrar a segunda dose da Vacina Oral de Rotavírus Humano a partir de 3 meses e 7 dias a 5 meses e 15 dias de idade (14 a 24 semanas de ida). O intervalo mínimo reconizado entre a primeira e a segunda dose é de 4 semanas.', 'Doenças diarréicas por Rotavírus', 'INFANT', null, '2020-12-04 17:28:28.952000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (145, 'DOSAGE_2', 4, null, 4, 'Vacina Oral contra a Pólio', 2, null, 'Poliomielite (paralisia Infantil)', 'INFANT', 146, '2020-12-04 17:28:28.088000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (156, 'DOSAGE_2', 4, null, 4, 'Vacina contra Pneumococos', 2, null, 'Otite, sinusite, pneumonias, meningite causadas pelo Streptococcus pneumoniae', 'INFANT', 157, '2020-12-04 17:28:27.262000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (149, 'DOSAGE_2', 4, null, 4, 'Vacina Tetravalente', 2, 'O esquema de vacinação atual é feito aos 2, 4 e 6 meses de idade com a vacina Tetravalente e dois reforços com a Tríplice Bacteriana (DTP). O primeiro reforço aos 15 meses e o segundo reforço entre 4 e 6 anos.', 'Difteria, tétano, coqueluche, meningite e outras infecções por Haemophilus influenzae tipo B', 'INFANT', 150, '2020-12-04 17:28:26.400000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (160, 'DOSAGE_2', 5, null, 5, 'Vacina contra Meningococo C', 10, null, 'Doença invasiva causada por Neisseria meningitidis do Sorogrupo C', 'INFANT', 161, '2020-12-04 17:28:24.577000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (143, 'DOSAGE_2', 6, null, 6, 'Vacina contra Hepatite B', null, 'A primeira dose da vacina contra a hepatite B deve ser administrada na maternidade, nas primeiras 12 horas de vida do recém-nascido. O esquema básico se constitui de 03 (três) doses, com intervalos de 30 dias da primeira para a segunda dose e 180 dias da primeira para a terceira dose.', 'Hepatite B', 'INFANT', null, '2020-12-04 17:28:16.011000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (146, 'DOSAGE_3', 6, null, 6, 'Vacina Oral contra a Pólio', 9, null, 'Poliomielite (paralisia Infantil)', 'INFANT', 147, '2020-12-04 17:28:04.691000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (150, 'DOSAGE_3', 6, null, 6, 'Vacina Tetravalente', 9, 'O esquema de vacinação atual é feito aos 2, 4 e 6 meses de idade com a vacina Tetravalente e dois reforços com a Tríplice Bacteriana (DTP). O primeiro reforço aos 15 meses e o segundo reforço entre 4 e 6 anos.', 'Difteria, tétano, coqueluche, meningite e outras infecções por Haemophilus influenzae tipo B', 'INFANT', 151, '2020-12-04 17:27:56.488000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (157, 'DOSAGE_3', 6, null, 6, 'Vacina contra Pneumococos', 6, null, 'Otite, sinusite, pneumonias, meningite causadas pelo Streptococcus pneumoniae', 'INFANT', 158, '2020-12-04 17:27:49.335000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (164, 'DOSAGE_1', 9, null, 9, 'Vacina contra febre amarela', null, 'A vacina contra febre amarela está indicada para crianças a partir dos 09 meses de idade e quando for viajar para o exterior, vacinar contra Febre Amarela 10 (dez) dias antes da viagem.', 'Febre amarela', 'INFANT', null, '2020-12-04 17:27:40.540000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (158, 'DOSAGE_REINFORCEMENT', 12, null, 12, 'Vacina contra Pneumococos', null, null, 'Otite, sinusite, pneumonias, meningite causadas pelo Streptococcus pneumoniae', 'INFANT', null, '2020-12-04 17:27:32.960000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (162, 'DOSAGE_1', 12, null, 12, 'Tríplice Viral', 36, null, 'Sarampo, Rubéola e Caxumba', 'INFANT', 163, '2020-12-04 17:27:26.286000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (147, 'DOSAGE_REINFORCEMENT', 15, null, 15, 'Vacina Oral contra a Pólio', null, null, 'Poliomielite (paralisia Infantil)', 'INFANT', null, '2020-12-04 17:27:19.486000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (151, 'DOSAGE_1_REINFORCEMENT', 15, null, 15, 'Vacina Tríplice Bacteriana', 33, 'O esquema de vacinação atual é feito aos 2, 4 e 6 meses de idade com a vacina Tetravalente e dois reforços com a Tríplice Bacteriana (DTP). O primeiro reforço aos 15 meses e o segundo reforço entre 4 e 6 anos.', 'Difteria, tétano, coqueluche', 'INFANT', 152, '2020-12-04 17:27:09.448000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (161, 'DOSAGE_REINFORCEMENT', 15, null, 15, 'Vacina contra Meningococo C', null, null, 'Doença invasiva causada por Neisseria meningitidis do Sorogrupo C', 'INFANT', null, '2020-12-04 17:27:02.391000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (163, 'DOSAGE_REINFORCEMENT', 72, null, 48, 'Tríplice Viral', null, null, 'Sarampo, Rubéola e Caxumba', 'INFANT', null, '2020-12-04 17:26:24.122000', 'A');
-- INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (152, 'DOSAGE_2_REINFORCEMENT', 72, null, 48, 'Vacina Tríplice Bacteriana', null, 'O esquema de vacinação atual é feito aos 2, 4 e 6 meses de idade com a vacina Tetravalente e dois reforços com a Tríplice Bacteriana (DTP). O primeiro reforço aos 15 meses e o segundo reforço entre 4 e 6 anos.', 'Difteria, tétano, coqueluche', 'INFANT', null, '2020-12-04 17:26:15.144000', 'A');

INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (25, 'DOSAGE_REINFORCEMENT', 72, null, 48, 'Tríplice Viral', null, null, 'Sarampo, Rubéola e Caxumba', 'INFANT', null, '2020-12-04 17:26:24.122000', 'A');
INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (24, 'DOSAGE_2_REINFORCEMENT', 72, null, 48, 'Vacina Tríplice Bacteriana', null, 'O esquema de vacinação atual é feito aos 2, 4 e 6 meses de idade com a vacina Tetravalente e dois reforços com a Tríplice Bacteriana (DTP). O primeiro reforço aos 15 meses e o segundo reforço entre 4 e 6 anos.', 'Difteria, tétano, coqueluche', 'INFANT', null, '2020-12-04 17:26:15.144000', 'A');
INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (23, 'DOSAGE_1_REINFORCEMENT', 15, null, 15, 'Vacina Tríplice Bacteriana', 33, 'O esquema de vacinação atual é feito aos 2, 4 e 6 meses de idade com a vacina Tetravalente e dois reforços com a Tríplice Bacteriana (DTP). O primeiro reforço aos 15 meses e o segundo reforço entre 4 e 6 anos.', 'Difteria, tétano, coqueluche', 'INFANT', 24, '2020-12-04 17:27:09.448000', 'A');
INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (22, 'DOSAGE_REINFORCEMENT', 15, null, 15, 'Vacina contra Meningococo C', null, null, 'Doença invasiva causada por Neisseria meningitidis do Sorogrupo C', 'INFANT', null, '2020-12-04 17:27:02.391000', 'A');
INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (21, 'DOSAGE_REINFORCEMENT', 15, null, 15, 'Vacina Oral contra a Pólio', null, null, 'Poliomielite (paralisia Infantil)', 'INFANT', null, '2020-12-04 17:27:19.486000', 'A');
INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (20, 'DOSAGE_REINFORCEMENT', 12, null, 12, 'Vacina contra Pneumococos', null, null, 'Otite, sinusite, pneumonias, meningite causadas pelo Streptococcus pneumoniae', 'INFANT', null, '2020-12-04 17:27:32.960000', 'A');
INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (19, 'DOSAGE_1', 12, null, 12, 'Tríplice Viral', 36, null, 'Sarampo, Rubéola e Caxumba', 'INFANT', 25, '2020-12-04 17:27:26.286000', 'A');
INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (18, 'DOSAGE_1', 9, null, 9, 'Vacina contra febre amarela', null, 'A vacina contra febre amarela está indicada para crianças a partir dos 09 meses de idade e quando for viajar para o exterior, vacinar contra Febre Amarela 10 (dez) dias antes da viagem.', 'Febre amarela', 'INFANT', null, '2020-12-04 17:27:40.540000', 'A');
INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (17, 'DOSAGE_2', 6, null, 6, 'Vacina contra Hepatite B', null, 'A primeira dose da vacina contra a hepatite B deve ser administrada na maternidade, nas primeiras 12 horas de vida do recém-nascido. O esquema básico se constitui de 03 (três) doses, com intervalos de 30 dias da primeira para a segunda dose e 180 dias da primeira para a terceira dose.', 'Hepatite B', 'INFANT', null, '2020-12-04 17:28:16.011000', 'A');
INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (16, 'DOSAGE_3', 6, null, 6, 'Vacina Oral contra a Pólio', 9, null, 'Poliomielite (paralisia Infantil)', 'INFANT', 21, '2020-12-04 17:28:04.691000', 'A');
INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (15, 'DOSAGE_3', 6, null, 6, 'Vacina contra Pneumococos', 6, null, 'Otite, sinusite, pneumonias, meningite causadas pelo Streptococcus pneumoniae', 'INFANT', 20, '2020-12-04 17:27:49.335000', 'A');
INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (14, 'DOSAGE_3', 6, null, 6, 'Vacina Tetravalente', 9, 'O esquema de vacinação atual é feito aos 2, 4 e 6 meses de idade com a vacina Tetravalente e dois reforços com a Tríplice Bacteriana (DTP). O primeiro reforço aos 15 meses e o segundo reforço entre 4 e 6 anos.', 'Difteria, tétano, coqueluche, meningite e outras infecções por Haemophilus influenzae tipo B', 'INFANT', 23, '2020-12-04 17:27:56.488000', 'A');
INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (13, 'DOSAGE_2', 5, null, 5, 'Vacina contra Meningococo C', 10, null, 'Doença invasiva causada por Neisseria meningitidis do Sorogrupo C', 'INFANT', 22, '2020-12-04 17:28:24.577000', 'A');
INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (12, 'DOSAGE_2', 4, null, 4, 'Vacina contra Pneumococos', 2, null, 'Otite, sinusite, pneumonias, meningite causadas pelo Streptococcus pneumoniae', 'INFANT', 15, '2020-12-04 17:28:27.262000', 'A');
INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (11, 'DOSAGE_2', 4, null, 4, 'Vacina Oral contra Rotavírus Humano', null, 'É possível administrar a segunda dose da Vacina Oral de Rotavírus Humano a partir de 3 meses e 7 dias a 5 meses e 15 dias de idade (14 a 24 semanas de ida). O intervalo mínimo reconizado entre a primeira e a segunda dose é de 4 semanas.', 'Doenças diarréicas por Rotavírus', 'INFANT', null, '2020-12-04 17:28:28.952000', 'A');
INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (10, 'DOSAGE_2', 4, null, 4, 'Vacina Oral contra a Pólio', 2, null, 'Poliomielite (paralisia Infantil)', 'INFANT', 16, '2020-12-04 17:28:28.088000', 'A');
INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (9, 'DOSAGE_2', 4, null, 4, 'Vacina Tetravalente', 2, 'O esquema de vacinação atual é feito aos 2, 4 e 6 meses de idade com a vacina Tetravalente e dois reforços com a Tríplice Bacteriana (DTP). O primeiro reforço aos 15 meses e o segundo reforço entre 4 e 6 anos.', 'Difteria, tétano, coqueluche, meningite e outras infecções por Haemophilus influenzae tipo B', 'INFANT', 14, '2020-12-04 17:28:26.400000', 'A');
INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (8, 'DOSAGE_1', 3, null, 3, 'Vacina contra Meningococo C', 2, null, 'Doença invasiva causada por Neisseria meningitidis do Sorogrupo C', 'INFANT', 13, '2020-12-04 17:28:29.793000', 'A');
INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (7, 'DOSAGE_1', 2, null, 2, 'Vacina Oral contra a Pólio', 2, null, 'Poliomielite (paralisia Infantil)', 'INFANT', 10, '2020-12-04 17:28:31.458000', 'A');
INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (6, 'DOSAGE_1', 2, null, 2, 'Vacina contra Pneumococos', 2, null, 'Otite, sinusite, pneumonias, meningite causadas pelo Streptococcus pneumoniae', 'INFANT', 12, '2020-12-04 17:28:30.607000', 'A');
INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (5, 'DOSAGE_1', 2, null, 2, 'Vacina Oral contra Rotavírus Humano', 2, 'É possível administar a primeira dose da Vacina Oral de Rotavírus Humano a partir de 1 mês e 15 dias a 3 meses e 7 dias de idade (6 a 14 semanas de vida)', 'Doenças diarréicas por Rotavírus', 'INFANT', 11, '2020-12-04 17:28:33.024000', 'A');
INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (4, 'DOSAGE_1', 2, null, 2, 'Vacina Tetravalente', 2, 'O esquema de vacinação atual é feito aos 2, 4 e 6 meses de idade com a vacina Tetravalente e dois reforços com a Tríplice Bacteriana (DTP). O primeiro reforço aos 15 meses e o segundo reforço entre 4 e 6 anos.', 'Difteria, tétano, coqueluche, meningite e outras infecções por Haemophilus influenzae tipo B', 'INFANT', 9, '2020-12-04 17:28:32.243000', 'A');
INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (3, 'DOSAGE_2', 1, null, 1, 'Vacina contra Hepatite B', 5, 'A primeira dose da vacina contra a hepatite B deve ser administrada na maternidade, nas primeiras 12 horas de vida do recém-nascido. O esquema básico se constitui de 03 (três) doses, com intervalos de 30 dias da primeira para a segunda dose e 180 dias da primeira para a terceira dose.', 'Hepatite B', 'INFANT', 17, '2020-12-04 17:28:33.728000', 'A');
INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (2, 'DOSAGE_1', 0, null, 0, 'Vacina contra Hepatite B', 1, 'A primeira dose da vacina contra a hepatite B deve ser administrada na maternidade, nas primeiras 12 horas de vida do recém-nascido. O esquema básico se constitui de 03 (três) doses, com intervalos de 30 dias da primeira para a segunda dose e 180 dias da primeira para a terceira dose.', 'Hepatite B', 'INFANT', 3, '2020-12-04 17:28:34.525000', 'A');
INSERT INTO public.vaccine (id, dosage, final_range, frequency, initial_range, name, next_dosage, observation, prevented_diseases, range, next_vaccine_id, create_at, situation) VALUES (1, 'DOSAGE_UNIQUE', 0, null, 0, 'BCG-ID', null, null, 'Formas graves de Tuberculose', 'INFANT', null, '2020-12-04 17:28:36.361000', 'A');